// js/angular/todo-list.component.ts
// todo-list.component.ts: Todo list component
//
// Description:
// Todo list component that obtains TodoService with inject() and renders with
// the built-in @for, @if, and @empty control flow blocks.
// Part of the Angular sample project; see main.ts and
// README.md in this directory for setup and requirements.
//
// Author: id774 (More info: https://id774.net)
// Source Code: https://github.com/id774/sandbox
// License: The GPL version 3, or LGPL version 3 (Dual License).
// Contact: idnanashi@gmail.com

import { Component, inject, input } from '@angular/core';

import { TodoService } from './todo.service';

@Component({
  selector: 'app-todo-list',
  template: `
    <h2>{{ heading() }} ({{ todos.remaining() }} left)</h2>

    <form (submit)="add($event, draft)">
      <input #draft placeholder="What next?" />
      <button type="submit">add</button>
    </form>

    <ul>
      <!-- track tells Angular how to identify a row across updates; it is
           required, unlike the optional trackBy of *ngFor -->
      @for (todo of todos.todos(); track todo.id) {
        <li [class.done]="todo.done">
          <input type="checkbox" [checked]="todo.done" (change)="todos.toggle(todo.id)" />
          {{ todo.text }}
          <button (click)="todos.remove(todo.id)">x</button>
        </li>
      } @empty {
        <li>nothing here yet</li>
      }
    </ul>
  `,
  styles: `.done { color: #999; text-decoration: line-through; }`,
})
export class TodoListComponent {
  readonly heading = input('Todo');

  // inject() in a field initialiser: no constructor, and the type is inferred.
  protected readonly todos = inject(TodoService);

  protected add(event: Event, input: HTMLInputElement): void {
    event.preventDefault();
    this.todos.add(input.value);
    input.value = '';
  }
}

// js/lit/todo-list.js
// todo-list.js: Todo list custom element
//
// Description:
// Todo list element with internal reactive state and list rendering through
// the repeat directive.
// Part of the Lit sample project; see index.html and
// README.md in this directory for setup and requirements.
//
// Author: id774 (More info: https://id774.net)
// Source Code: https://github.com/id774/sandbox
// License: The GPL version 3, or LGPL version 3 (Dual License).
// Contact: idnanashi@gmail.com

import { css, html, LitElement } from "lit";
import { repeat } from "lit/directives/repeat.js";

let nextId = 1;

class TodoList extends LitElement {
  static properties = {
    heading: { type: String },
    // state: true means internal — not reflected to an attribute, but still
    // triggers a re-render when reassigned.
    _todos: { state: true },
  };

  static styles = css`
    ul { list-style: none; padding: 0; }
    li.done { color: #999; text-decoration: line-through; }
  `;

  constructor() {
    super();
    this.heading = "Todo";
    this._todos = [];
  }

  render() {
    const remaining = this._todos.filter((t) => !t.done).length;

    return html`
      <h2>${this.heading} (${remaining} left)</h2>

      <form @submit=${this.#add}>
        <input name="text" placeholder="What next?" />
        <button type="submit">add</button>
      </form>

      <ul>
        ${repeat(
          this._todos,
          (todo) => todo.id, // key: DOM nodes are moved, not rebuilt
          (todo) => html`
            <li class=${todo.done ? "done" : ""}>
              <input type="checkbox" .checked=${todo.done} @change=${() => this.#toggle(todo.id)} />
              ${todo.text}
              <button @click=${() => this.#remove(todo.id)}>x</button>
            </li>
          `,
        )}
      </ul>
    `;
  }

  #add(event) {
    event.preventDefault();
    const input = event.target.elements.text;
    const text = input.value.trim();
    if (!text) return;
    // Reassignment, not push(): Lit compares by identity to decide on a render.
    this._todos = [...this._todos, { id: nextId++, text, done: false }];
    input.value = "";
  }

  #toggle(id) {
    this._todos = this._todos.map((t) => (t.id === id ? { ...t, done: !t.done } : t));
  }

  #remove(id) {
    this._todos = this._todos.filter((t) => t.id !== id);
  }
}

customElements.define("todo-list", TodoList);
