// js/solidjs/counter.jsx
// counter.jsx: Solid counter with signals, a memo, and an effect
//
// Description:
// Counter component built from createSignal, createMemo, and createEffect.
//
// Author: id774 (More info: https://id774.net)
// Source Code: https://github.com/id774/sandbox
// License: The GPL version 3, or LGPL version 3 (Dual License).
// Contact: idnanashi@gmail.com
//
// Build / Run:
//     npm create vite@latest solid-demo -- --template solid
//     cd solid-demo && npm install
//     cp ../counter.jsx src/
//     npm run dev
//
// Requirements:
// - Node.js 20.19 or later (the engines of the Vite release the scaffold installs)
// - npm
// - Solid 1.9 or later within the 1.x line (solid-js), with the Vite Solid
//   template

// The body of a Solid component runs once, at creation. Anything that should
// change over time has to be a signal read *inside* the JSX, which is where
// the fine-grained subscription is set up.
//
//   import { render } from "solid-js/web";
//   render(() => <Counter step={2} />, document.getElementById("root"));

import { createEffect, createMemo, createSignal, onCleanup } from "solid-js";

export default function Counter(props) {
  const [count, setCount] = createSignal(0);
  const doubled = createMemo(() => count() * 2);

  // No dependency array: the effect tracks whatever signals it reads.
  createEffect(() => {
    document.title = `count: ${count()}`;
  });

  return (
    <p>
      {/* `count()` here, not `count` — the call is the subscription */}
      <output>{count()} (doubled: {doubled()})</output>
      <button onClick={() => setCount((c) => c + (props.step ?? 1))}>
        +{props.step ?? 1}
      </button>
      <button onClick={() => setCount(0)} disabled={count() === 0}>
        reset
      </button>
    </p>
  );
}

export function Ticker() {
  const [seconds, setSeconds] = createSignal(0);
  const id = setInterval(() => setSeconds((s) => s + 1), 1000);

  // Runs when the owning component is disposed.
  onCleanup(() => clearInterval(id));

  return <p>{seconds()}s elapsed</p>;
}

// js/svelte/Counter.svelte
<script>
  // Counter.svelte: Svelte 5 counter with runes
  //
  // Description:
  // Counter component using $props, $state, $derived, and $effect.
  //
  // Author: id774 (More info: https://id774.net)
  // Source Code: https://github.com/id774/sandbox
  // License: The GPL version 3, or LGPL version 3 (Dual License).
  // Contact: idnanashi@gmail.com
  //
  // Build / Run:
  //     npm create vite@latest svelte-demo -- --template svelte
  //     cd svelte-demo && npm install
  //     cp ../Counter.svelte ../TodoList.svelte ../counter.svelte.js src/lib/
  //     npm run dev
  //
  // Requirements:
  // - Node.js 20.19 or later (the engines of the Vite release the scaffold installs)
  // - npm
  // - Svelte 5 or later within the 5.x line, with the Vite Svelte template

  // Svelte 5 runes. `$props()` destructures what the parent passed, with
  // defaults; `$state` marks a variable the compiler should track.
  let { step = 1, label = "count" } = $props();

  let count = $state(0);
  let doubled = $derived(count * 2);

  // $effect runs after the DOM updates, and re-runs when the state it read
  // changes — here, `count`.
  $effect(() => {
    document.title = `${label}: ${count}`;
  });
</script>

<p>
  <output>{label}: {count} (doubled: {doubled})</output>
  <button onclick={() => (count += step)}>+{step}</button>
  <button onclick={() => (count -= step)}>-{step}</button>
  <button onclick={() => (count = 0)} disabled={count === 0}>reset</button>
</p>

{#if count > 10}
  <p class="warn">over ten</p>
{/if}

<style>
  .warn {
    color: crimson;
  }
</style>
